baseurl = "https://hugo.kulow.org"
title = "Sonja G"
theme = "minimal-portfolio"
languageCode = "de-de"

[params]
  brand = "Sonja G"
  description = "Portfolio von Sonja G"
  copyright = "&copy;2023 Sonja G"
  
  hero_zeile1 = "highest Design aus Nürnberg."
  hero_zeile2 = "begeisternde Designlösungen, plattformübergreifend nachhaltig und effektiv"
  
  # Navigation
  [[params.navlinks]]
  name = "Portfolio"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "Impressum"
  url = "impressum"

  [[params.navlinks]]
  name = "Fragen?"
  url = "contact"

[module]
[module.hugoVersion]
# We use hugo.Deps to list dependencies, which was added in Hugo 0.92.0
min = "0.92.0"

[[module.imports]]
path="github.com/gohugoio/hugo-mod-bootstrap-scss/v5"